#ifndef RPICAMERA_CONFIG_H
#define RPICAMERA_CONFIG_H

#define RPICAMERA_VERSION_MAJOR @RPICAMERA_VERSION_MAJOR@
#define RPICAMERA_VERSION_MINOR @RPICAMERA_VERSION_MINOR@

#endif // RPICAMERA_CONFIG_H
